export {default as Landing} from './landing.jsx'
export {default as Images} from './images.jsx'
export {default as LandigPart2} from './landig-second-part.jsx'
export {default as ExprienceSection} from './exprience-section.jsx'
export {default as PolicySection} from './policy-section.jsx'
export {default as VideoSection} from './video.jsx'