name: Pull Request

on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build
        run: docker build .